# Para lintear y formatee tu código Python en cada push o pull request.
name: Python Code Quality

on: [push, pull_request]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Asegúrate que coincida con tu Dockerfile
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
        # Si tienes requirements.txt y quieres lint esos también (opcional)
        # pip install -r requirements.txt
    - name: Lint with Flake8
      run: |
        # Detiene el build si hay errores de Flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Salir con cero significa que no hay errores, o salir con un número para errores
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check formatting with Black
      run: |
        black --check .